services:
  - type: web
    name: rais-crm
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_FIREBASE_API_KEY
        fromEnv: NEXT_PUBLIC_FIREBASE_API_KEY
      - key: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
        fromEnv: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
      - key: NEXT_PUBLIC_FIREBASE_PROJECT_ID
        fromEnv: NEXT_PUBLIC_FIREBASE_PROJECT_ID
      - key: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
        fromEnv: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
      - key: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        fromEnv: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      - key: NEXT_PUBLIC_FIREBASE_APP_ID
        fromEnv: NEXT_PUBLIC_FIREBASE_APP_ID